# List orgs and repos here
# config['orgs']['{your_org}']['repos']['{your_repo}']
orgs:
    your_org1:
        repos:          # can also be repos: [repo1, repo2]
            - repo1
            - repo2
  
# General required configs here
general:
    branch:
        branch_name:
        create_branch:
    commit:
        git_add:
        commit_message:
    pull_request:
        create_pr:
        title:
        body:
        base:
    remove_repo:
    remove_tmp_dir:

# Variables needed in action file
extra_vars:
    source_file:
    destination_file: