# List orgs and repos here
orgs:
    your_org1:
        repos:
            - repo1
            - repo2
    your_org2:
        repos: [repo1, repo2]
        
# General required configs here
general:
    branch:
        branch_name: add-contributing
        create_branch: yes
    commit:
        git_add:
            - path/to/CONTRIBUTING.md
        commit_message: Add CONTRIBUTING
    pull_request:
        create_pr: yes
        title: Add CONTRIBUTING
        body: Adds a CONTRIBUTING file to the repo
        base: master
    remove_repo: yes
    remove_tmp_dir: yes

# Variables needed in action file
extra_vars:
    source_file: /path/to/git-manager/actions/add-file-static/CONTRIBUTING.md
    destination_file: path/to/CONTRIBUTING.md