# List orgs and repos here
orgs:
    JakeQuilty:
        repos:
            - git-manager-test-01
        
# General required configs here
general:
    branch:
        branch_name: update-pr-template
        create_branch: yes
    commit:
        git_add:
            - .github/PULL_REQUEST_TEMPLATE.md
        commit_message: Update PR template wording
    pull_request:
        create_pr: yes
        title: Update PR Template to use GitHub Keywords
        body:
        base: master
    remove_repo: yes
    remove_tmp_dir: yes

# Variables needed in action file
extra_vars:
    # Path to file to be edited. Assume file path from inside repo folder
    # ex) actions/replace-string-in-file/config.yml
    file: .github/PULL_REQUEST_TEMPLATE.md
    # String to replace
    old_string: Connected to
    # New value to change to
    new_string: Resolves
    # Replace all occurences of <old_string> with <new_string>
    # 'yes' - Replace all
    # 'no' - Replace only first occurence
    replace_all: no